### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by C3n7ral051nt4g3ncy**
# Pull Request 

Updating the Repository to my [own profile,](https://github.com/C3n7ral051nt4g3ncy) which has more information and Tools.
There is a link to my org on my personal profile.

### CODE REVIEW

**Comment by C3n7ral051nt4g3ncy** [comment]
I also added @Jocephus and @soxoj, 2 important people in the OSINT community. 👍

**Comment by C3n7ral051nt4g3ncy** [comment]
Added [Justin Seitz](https://twitter.com/jms_dot_py), founder of Hunchly and a great contributor to the world of OSINT and Python Automation.

**Comment by cqcore** [comment]
> Added [Justin Seitz](https://twitter.com/jms_dot_py), founder of Hunchly and a great contributor to the world of OSINT and Python Automation.

Got Hunchly in another repo, but added all the other great additions

**Comment by C3n7ral051nt4g3ncy** [comment]
> > Added [Justin Seitz](https://twitter.com/jms_dot_py), founder of Hunchly and a great contributor to the world of OSINT and Python Automation.
> 
> Got Hunchly in another repo, but added all the other great additions

Thanks, will close the PR

**Comment by C3n7ral051nt4g3ncy** [comment]
Closing PR #1

**Pull request closed without merging**
